#!/bin/bash
FEH="feh --bg-scale ~/wallpaper.jpg &"
COMPOSER="picom &"
CONKY="(conky | while read LINE; do xsetroot -name \"\$LINE\"; done) &"
DWM="exec dwm"
printf "$FEH\n$COMPOSER\n$CONKY\n$DWM\n" > ~/.xinitrc
startx
