#!/bin/bash
COMPOSER="picom &"
FEH="feh --bg-scale ~/wallpaper.jpg &"
NOTIFICATIONS="dunst &"
CONKY="(conky | while read LINE; do xsetroot -name \"\$LINE\"; done) &"
DWM="exec dwm"
printf "$COMPOSER\n$FEH\n$NOTIFICATIONS\n$CONKY\n$DWM\n" > ~/.xinitrc
startx