install:
	ln -s ../lib/node_modules/http-share/bin/http-share /bin/http-share
	ln -s ../../../lib/node_modules/http-share/doc/http-share.1 /usr/local/man/man1/http-share.1

uninstall: 
	unlink /bin/http-share
	unlink /usr/local/man/man1/http-share.1